### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by bakamarimo** [tetrix1993/yandere-pool-downloader#1]
![Screenshot (701)](https://user-images.githubusercontent.com/86364806/124377315-ff50fe00-dcc8-11eb-910f-87c04f51ff84.png)
attached the ss, it downloaded 2 pools and after that it says this

**Comment by tetrix1993** [comment]
This repo is outdated and I will no longer update it. Please check out https://github.com/tetrix1993/yandere-downloader instead.

**Comment by bakamarimo** [comment]
> This repo is outdated and I will no longer update it. Please check out https://github.com/tetrix1993/yandere-downloader instead.

thank you for replying . will do the one u mentioned
